
// This file has been generated by the GUI designer. Do not modify.
namespace FRepDesigner
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action customFRepAction;
		private global::Gtk.Action rFunctionAction;
		private global::Gtk.Action zoomInAction;
		private global::Gtk.Action zoomOutAction;
		private global::Gtk.Action selectAction;
		private global::Gtk.Action newSphereAction;
		private global::Gtk.Action undoAction;
		private global::Gtk.Action redoAction;
		private global::Gtk.Action preferencesAction;
		private global::Gtk.Action newAction;
		private global::Gtk.Action openAction;
		private global::Gtk.Action saveAction;
		private global::Gtk.Action saveAsAction;
		private global::Gtk.Action stopAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.Toolbar toolbar1;
		private global::Gtk.Image image1;
		private global::Gtk.Statusbar statusbar1;
		private global::Gtk.ComboBox comboboxTracer;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FRepDesigner.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Tools");
			this.customFRepAction = new global::Gtk.Action ("customFRepAction", global::Mono.Unix.Catalog.GetString ("Custom"), null, "package");
			this.customFRepAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Custom");
			w2.Add (this.customFRepAction, null);
			this.rFunctionAction = new global::Gtk.Action ("rFunctionAction", global::Mono.Unix.Catalog.GetString ("R-Function"), global::Mono.Unix.Catalog.GetString ("R-Function"), "function");
			this.rFunctionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("R-Function");
			w2.Add (this.rFunctionAction, null);
			this.zoomInAction = new global::Gtk.Action ("zoomInAction", global::Mono.Unix.Catalog.GetString ("Zoom In"), null, "gtk-zoom-in");
			this.zoomInAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zoom In");
			w2.Add (this.zoomInAction, null);
			this.zoomOutAction = new global::Gtk.Action ("zoomOutAction", global::Mono.Unix.Catalog.GetString ("Zoom Out"), null, "gtk-zoom-out");
			this.zoomOutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zoom Out");
			w2.Add (this.zoomOutAction, null);
			this.selectAction = new global::Gtk.Action ("selectAction", global::Mono.Unix.Catalog.GetString ("_Select"), null, "cursor");
			this.selectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Select");
			w2.Add (this.selectAction, null);
			this.newSphereAction = new global::Gtk.Action ("newSphereAction", global::Mono.Unix.Catalog.GetString ("Sphere"), null, "gtk-yes");
			this.newSphereAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Sphere");
			w2.Add (this.newSphereAction, null);
			this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("Undo"), null, "gtk-undo");
			this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Undo");
			w2.Add (this.undoAction, null);
			this.redoAction = new global::Gtk.Action ("redoAction", global::Mono.Unix.Catalog.GetString ("Redo"), null, "gtk-redo");
			this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Redo");
			w2.Add (this.redoAction, null);
			this.preferencesAction = new global::Gtk.Action ("preferencesAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, "gtk-preferences");
			this.preferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w2.Add (this.preferencesAction, null);
			this.UIManager.InsertActionGroup (w2, 1);
			global::Gtk.ActionGroup w3 = new global::Gtk.ActionGroup ("File");
			this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-new");
			this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
			w3.Add (this.newAction, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
			w3.Add (this.openAction, null);
			this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
			w3.Add (this.saveAction, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save As..."), null, "gtk-save-as");
			this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As...");
			w3.Add (this.saveAsAction, null);
			this.stopAction = new global::Gtk.Action ("stopAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, "gtk-stop");
			this.stopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w3.Add (this.stopAction, null);
			this.UIManager.InsertActionGroup (w3, 2);
			global::Gtk.ActionGroup w4 = new global::Gtk.ActionGroup ("Help");
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About..."), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About...");
			w4.Add (this.aboutAction, null);
			this.UIManager.InsertActionGroup (w4, 3);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "FRepDesigner.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("F-Rep Designer");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DefaultWidth = 640;
			this.DefaultHeight = 480;
			// Container child FRepDesigner.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='stopAction' action='stopAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><separator/><toolitem name='undoAction' action='undoAction'/><toolitem name='redoAction' action='redoAction'/><separator/><toolitem name='zoomInAction' action='zoomInAction'/><toolitem name='zoomOutAction' action='zoomOutAction'/><separator/><toolitem name='selectAction' action='selectAction'/><toolitem name='newSphereAction' action='newSphereAction'/><toolitem name='rFunctionAction' action='rFunctionAction'/><separator/><toolitem name='preferencesAction' action='preferencesAction'/><separator/><toolitem name='stopAction' action='stopAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
			this.vbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.CanFocus = true;
			this.image1.Name = "image1";
			this.vbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.image1]));
			w7.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.comboboxTracer = global::Gtk.ComboBox.NewText ();
			this.comboboxTracer.Name = "comboboxTracer";
			this.statusbar1.Add (this.comboboxTracer);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.comboboxTracer]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.customFRepAction.Activated += new global::System.EventHandler (this.OnCustomFRepActionActivated);
			this.rFunctionAction.Activated += new global::System.EventHandler (this.OnRFunctionActionActivated);
			this.zoomInAction.Activated += new global::System.EventHandler (this.OnZoomInActionActivated);
			this.zoomOutAction.Activated += new global::System.EventHandler (this.OnZoomOutActionActivated);
			this.selectAction.Activated += new global::System.EventHandler (this.OnSelectActionActivated);
			this.newSphereAction.Activated += new global::System.EventHandler (this.OnSphereActionActivated);
			this.undoAction.Activated += new global::System.EventHandler (this.OnUndoActionActivated);
			this.redoAction.Activated += new global::System.EventHandler (this.OnRedoActionActivated);
			this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
			this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
			this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
			this.stopAction.Activated += new global::System.EventHandler (this.OnStopActionActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.image1.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnImage1SizeAllocated);
			this.comboboxTracer.Changed += new global::System.EventHandler (this.OnComboboxTracerChanged);
		}
	}
}
